name: laborky_UJEP 
version: '1.0.0'

services:
 database:
  image: postgres
  container_name: laborky_db
  restart: unless-stopped
  environment:
   PGPASSWORD: postgres
   POSTGRES_PASSWORD: postgres
   PGDATABASE: railway
   POSTGRES_DB: postgres
   PGDATA: /var/lib/postgresql/new_data
  volumes:
   - ./database/db/pg_dump.sql:/docker-entrypoint-initdb.d/seed.sql
   - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
   - ./database/data:/var/lib/postgresql/new_data
  networks:
   laborky_network:
    ipv4_address: 172.254.5.4

 frontend:
  build:
   context: FrontEnd
   args:
    NEXT_PUBLIC_BASE: "http://localhost:3000"
    NEXT_PUBLIC_API_URL: "http://backend:9999"
    NEXT_PUBLIC_TIME_GAP: 8
    NEXT_PUBLIC_STAG_SERVER: "https://stag-demo.zcu.cz/ws"
  container_name: laborky_FE
  restart: unless-stopped
  ports:
   - '3000:3000'
  depends_on:
   - database
   - backend
  networks:
   laborky_network:
    ipv4_address: 172.254.5.3

 backend:
  build:
   context: BackEnd
   args:
     PORT: "9999" 
     HOST: "0.0.0.0"
     DB_URL: "postgresql://postgres:postgres@database:5432/railway"
     INTERVAL_VYPISU_DNY: 14 
     STAG_URL: "https://stag-demo.zcu.cz/"
     MIN_TIME_ODZAPIS: 8 
     INTERVAL_ZOBRAZENI_HODINY: 4
  container_name: laborky_BE
  restart: unless-stopped
  depends_on:
   - database
  networks:
   laborky_network:
    ipv4_address: 172.254.5.5

networks:
 laborky_network:
  name: laborky
  attachable: true
  ipam:
   config:
    - subnet: 172.254.5.0/24
      ip_range: 172.254.5.0/24
      gateway: 172.254.5.254
